global:
  scrape_interval: 5s       
  evaluation_interval: 5s  

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: 'prometheus'

  - job_name: 'workingspaces'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5189']
        labels:
          app: 'workingspaces'